{
  "headers": {
    "client_id": "7e8ccbe9ab2443f5a1b501f25e95f8f7",
    "client_secret": "5bE3830FfC09449AbbC60427c3eCD7C9",
    "grant_type": "CLIENT_CREDENTIALS",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.26.8",
    "accept": "*/*",
    "postman-token": "f4a5b728-ec24-418c-b77c-3b8cd93e89ee",
    "host": "localhost:8081",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "94"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/transformdata",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": null,
  "listenerPath": "/transformdata",
  "relativePath": "/transformdata",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/transformdata",
  "rawRequestPath": "/transformdata",
  "remoteAddress": "/127.0.0.1:59620",
  "requestPath": "/transformdata"
}